version: '1'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: phpproj
      MYSQL_USER: pa
      MYSQL_ROOT_PASSWORD: E*V$5Z#6BkuFZkB
      MYSQL_PASSWORD: E*V$5Z#6BkuFZkB
    volumes:
      - db-data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  db-data: